### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by KalvinThien** [charmparticle/tiktokget#3]
when i play ,i have a trouble, can you help me ?

C:\Users\Admin\Downloads\tiktokget-main\tiktokget-main>py tiktokget @led_du_go
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\tiktokget-main\tiktokget-main\tiktokget", line 49, in <module>
    driver = webdriver.Firefox(options=opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by charmparticle** [comment]
This is why I removed Windows - it just generally makes things harder.

In this case, you need to install Firefox. and geckodriver, and also add the binary paths to your system path, so that selenium knows where to look to launch firefox. More info here:

https://www.maketecheasier.com/what-is-the-windows-path/
