### ISSUE TITLE
tiktokget error  - selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status signal

### ISSUE THREAD

**Issue by estatistics** [charmparticle/tiktokget#9]
linux, bullseye11

``` DeprecationWarning: headless property is deprecated, instead use add_argument('-headless')
  opts.headless = True
Traceback (most recent call last):
  File "/home/elias/.local/bin/tiktokget", line 49, in <module>
    driver = webdriver.Firefox(options=opts)
  File "/home/elias/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 196, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/home/elias/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/elias/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/elias/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/elias/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status signal
```

**Comment by charmparticle** [comment]
upgrade to the newest, then use -f to interact with the browser
